baseURL = 'https://nanoelbow.github.io/learnings/'
languageCode = 'en-us'
title = 'Learnings'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  style = "dracula"
  lineNos = true
